/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   Do not edit this file directly. Any changes will be lost.           ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import type { actions as ListReportActions, assertions as ListReportAssertions } from "sap/fe/test/ListReport";
import type { actions as ObjectPageActions, assertions as ObjectPageAssertions } from "sap/fe/test/ObjectPage";
import type { actions as TemplatePageActions, assertions as TemplatePageAssertions } from "sap/fe/test/TemplatePage";
import type Shell from "sap/fe/test/Shell";
import type BaseArrangements from "sap/fe/test/BaseArrangements";
import type { actions as LabelParameterListGeneratedCustomActions, assertions as LabelParameterListGeneratedCustomAssertions } from "../pages/LabelParameterList.gen";
import type { actions as LabelParameterObjectPageGeneratedCustomActions, assertions as LabelParameterObjectPageGeneratedCustomAssertions } from "../pages/LabelParameterObjectPage.gen";

export type Given = Opa5 & BaseArrangements & {
    iTearDownMyApp: () => Given;
    iStartMyApp: (sAppHash?: string, mInUrlParameters?: object) => Given;
    and: Given;
};

export type When = Opa5 & BaseArrangements & {
    onTheLabelParameterListGenerated: Opa5 & ListReportActions & TemplatePageActions & typeof LabelParameterListGeneratedCustomActions;
    onTheLabelParameterObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof LabelParameterObjectPageGeneratedCustomActions;
    onTheShell: Shell;
};

export type Then = Opa5 & BaseArrangements & {
    onTheLabelParameterListGenerated: Opa5 & ListReportAssertions & TemplatePageAssertions & typeof LabelParameterListGeneratedCustomAssertions;
    onTheLabelParameterObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof LabelParameterObjectPageGeneratedCustomAssertions;
    onTheShell: Shell;
};
