/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes.gen";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("LabelParameterListListReport journey");

    const defaultTableId = "";

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();

        Then.onTheLabelParameterListGenerated.iSeeThisPage();
    });

    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheLabelParameterListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
        Then.onTheLabelParameterListGenerated.onFilterBar().iCheckFilterField({ property: "InspectionLot" });
    });

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onTheLabelParameterListGenerated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onTheLabelParameterListGenerated.onFilterBar().iExecuteSearch();
    //     Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckRows();
    // });

    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        // When.onTheLabelParameterListGenerated.onTable(defaultTableId).iPressAction("Print Sample Label");
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckAction("Print Sample Label", { enabled: false });
        // When.onTheLabelParameterListGenerated.onTable(defaultTableId).iPressAction("Print Hold Label");
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckAction("Print Hold Label", { enabled: false });
        // When.onTheLabelParameterListGenerated.onTable(defaultTableId).iPressAction("Print Released Label");
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckAction("Print Released Label", { enabled: false });
        // When.onTheLabelParameterListGenerated.onTable(defaultTableId).iPressAction("Print Rejected Label");
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckAction("Print Rejected Label", { enabled: false });
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Plant":{"header":"Plant"},"InspectionLot":{"header":"Inspection Lot Number"}});
    });

    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        When.onTheLabelParameterListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheLabelParameterListGenerated.onTable(defaultTableId).iCheckRows();
        When.onTheLabelParameterListGenerated.onTable(defaultTableId).iPressRow(0);
        Then.onTheLabelParameterObjectPageGenerated.iSeeThisPage();
    });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
