/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes.gen";
import type { FormIdentifier } from "sap/fe/test/api/FormAPI";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("LabelParameterObjectPageObjectPage journey");

    opaTest("Navigate to LabelParameterObjectPageObjectPage", function (Given: Given, When: When, Then: Then) {
        Given.iStartMyApp();
        When.onTheLabelParameterListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheLabelParameterListGenerated.onTable("").iCheckRows();
        When.onTheLabelParameterListGenerated.onTable("").iPressRow(0);

        Then.onTheLabelParameterObjectPageGenerated.iSeeThisPage();
    });



    opaTest("Check body sections of the Object Page", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheLabelParameterObjectPageGenerated.iCheckSection({ section: "GeneralInfo" }, {});
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "Plant" });
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "InspectionLot" });
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "SampleQty" });
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "SampleDate" });
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "HoldReason" });
        Then.onTheLabelParameterObjectPageGenerated.onForm({ section: "GeneralInfo" } as unknown as FormIdentifier).iCheckField({ property: "RejectedReason" });
   });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
